/*USER*/
export const GET_SEARCH_USER = 'GET_SEARCH_USER';
export const GET_USERS = 'GET_USERS';
export const USER_MANAGER_LOADING = 'USER_MANAGER_LOADING';
/*AUTH*/
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const NO_TOKEN = 'NO_TOKEN';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT_LOADING = "LOGOUT_LOADING";
/*GALLERY*/
export const IMAGES_LOADING = "IMAGES_LOADING";
export const IMAGES_LOADED = "IMAGES_LOADED";
export const ERROR_LOADING_IMAGES = "ERROR_LOADING_IMAGES";
/*CATEGORY*/
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_LOADED = "CATEGORIES_LOADED";
export const ERROR_LOADING_CATEGORIES = "ERROR_LOADING_CATEGORIES";

/*ERROR*/
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SEARCH_USER_LOADING = 'SEARCH_USER_LOADING';



